// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentACarPortal.Data;

#nullable disable

namespace RentACarPortal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260717222720_FixContractRelationshipAndStatus")]
    partial class FixContractRelationshipAndStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.28");

            modelBuilder.Entity("RentACarPortal.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateOfIssue")
                        .HasColumnType("TEXT");

                    b.Property<double>("Deposit")
                        .HasColumnType("REAL");

                    b.Property<int>("DrivingLicenseNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FuelRecieved")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FuelReturned")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("FullTankSizeLiquid")
                        .HasColumnType("REAL");

                    b.Property<bool>("Insurance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonalNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlaceOfIssue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisterNumberOfVehicle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RentDriver")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("RentalEndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RentalEndPlace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("RentalEndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("RentalStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RentalStartPlace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("RentalStartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("RentalStation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeOfVehicle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("RentACarPortal.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RentACarPortal.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ACtype")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BootSpace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("DailyRate")
                        .HasColumnType("REAL");

                    b.Property<string>("DriveTerrain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("FuelEfficiency")
                        .HasColumnType("REAL");

                    b.Property<double>("FuelTankSize")
                        .HasColumnType("REAL");

                    b.Property<bool>("HasChildrenSafety")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasInsurance")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasNavigation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDiesel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegisterNumberOfVehicle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeOfVehicle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("RentACarPortal.Models.Contract", b =>
                {
                    b.HasOne("RentACarPortal.Models.User", "User")
                        .WithMany("Contracts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RentACarPortal.Models.Vehicle", b =>
                {
                    b.HasOne("RentACarPortal.Models.User", "User")
                        .WithMany("Vehicles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RentACarPortal.Models.User", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
